import { ChevronLeft, ChevronRight, ExternalLink, FileText, Loader2, ZoomIn, ZoomOut } from 'lucide-react'
import pdfWorkerUrl from 'pdfjs-dist/legacy/build/pdf.worker.min.mjs?url'
import { useEffect, useRef, useState } from 'react'

export function PdfPreview({ url, filename }: { url: string; filename: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const stageRef = useRef<HTMLDivElement>(null); const topScrollRef = useRef<HTMLDivElement>(null)
  const [pageNumber, setPageNumber] = useState(1); const [pageCount, setPageCount] = useState(0); const [zoom, setZoom] = useState(1); const [scrollWidth, setScrollWidth] = useState(0); const [status, setStatus] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle')
  useEffect(() => { setPageNumber(1); setPageCount(0) }, [url])
  useEffect(() => { if (!url) return; let cancelled = false; let loadingTask: { destroy: () => Promise<void> | void } | undefined; const render = async () => { setStatus('loading'); try { const response = await fetch(url, url.startsWith('blob:') ? undefined : { credentials: 'include' }); if (!response.ok) throw new Error('Invoice PDF is unavailable'); const pdfjs = await import('pdfjs-dist/legacy/build/pdf.mjs'); if (cancelled) return; pdfjs.GlobalWorkerOptions.workerSrc = pdfWorkerUrl; const task = pdfjs.getDocument({ data: new Uint8Array(await response.arrayBuffer()) }); loadingTask = task; const pdf = await task.promise; const page = await pdf.getPage(Math.min(Math.max(pageNumber, 1), pdf.numPages)); const canvas = canvasRef.current; const context = canvas?.getContext('2d'); if (!canvas || !context || cancelled) return; setPageCount(pdf.numPages); const viewport = page.getViewport({ scale: 1.25 * zoom }); canvas.width = Math.ceil(viewport.width); canvas.height = Math.ceil(viewport.height); await page.render({ canvas, canvasContext: context, viewport }).promise; if (!cancelled) setStatus('ready') } catch { if (!cancelled) setStatus('error') } }; void render(); return () => { cancelled = true; void loadingTask?.destroy() } }, [url, pageNumber, zoom])
  useEffect(() => { const stage = stageRef.current; if (!stage) return; const update = () => setScrollWidth(stage.scrollWidth); update(); if (typeof ResizeObserver === 'undefined') return; const observer = new ResizeObserver(update); observer.observe(stage); if (canvasRef.current) observer.observe(canvasRef.current); return () => observer.disconnect() }, [url, pageNumber, zoom, status])
  return <aside className="pdf-preview"><div className="pdf-preview-title"><FileText size={17} /><strong>{filename || 'Invoice'}</strong></div>{url ? <><div className="pdf-toolbar"><div className="pdf-page-controls"><button className="icon-button" aria-label="Previous page" disabled={pageNumber <= 1} onClick={() => setPageNumber((n) => n - 1)}><ChevronLeft size={15} /></button><span>{pageCount ? `Page ${pageNumber} of ${pageCount}` : 'Loading PDF'}</span><button className="icon-button" aria-label="Next page" disabled={!pageCount || pageNumber >= pageCount} onClick={() => setPageNumber((n) => n + 1)}><ChevronRight size={15} /></button></div><div className="pdf-zoom-controls"><button className="icon-button" aria-label="Zoom out" disabled={zoom <= .75} onClick={() => setZoom((n) => Number((n - .25).toFixed(2)))}><ZoomOut size={15} /></button><span>{Math.round(zoom * 100)}%</span><button className="icon-button" aria-label="Zoom in" disabled={zoom >= 1.75} onClick={() => setZoom((n) => Number((n + .25).toFixed(2)))}><ZoomIn size={15} /></button><a className="outline-button pdf-open-link" href={url} target="_blank" rel="noreferrer"><ExternalLink size={14} /> Open PDF</a></div></div><div ref={topScrollRef} className="pdf-horizontal-scroll" onScroll={(e) => { if (stageRef.current) stageRef.current.scrollLeft = e.currentTarget.scrollLeft }}><div style={{ width: scrollWidth }} /></div><div ref={stageRef} className="pdf-canvas-stage" aria-live="polite" onScroll={(e) => { if (topScrollRef.current) topScrollRef.current.scrollLeft = e.currentTarget.scrollLeft }}><canvas ref={canvasRef} className="pdf-canvas" aria-label={`Page ${pageNumber} of ${filename || 'invoice'}`} />{status === 'loading' ? <div className="pdf-loading"><Loader2 className="spin" size={20} /><span>Loading invoice...</span></div> : null}{status === 'error' ? <div className="pdf-error"><FileText size={30} /><strong>We could not display this PDF here.</strong><a className="outline-button" href={url} target="_blank" rel="noreferrer"><ExternalLink size={14} /> Open PDF</a></div> : null}</div></> : <div className="preview-empty"><FileText size={34} /><span>Choose a PDF to view it here.</span></div>}</aside>
}
