import { AlertTriangle, CheckCircle2, Pencil, X } from 'lucide-react'
import { useState, type ReactNode } from 'react'

type Issue = { message?: string; field_name?: string; field?: string; severity?: string }

export function ReviewerDecisionPanel({ pdf, title, fields, issues, canDecide, status, busy, error, onApprove, onReject, onCorrection }: { pdf: ReactNode; title: string; fields: Array<[string, string]>; issues: Issue[]; canDecide: boolean; status: ReactNode; busy: boolean; error?: string; onApprove: () => void; onReject: (notes: string) => void; onCorrection: (notes: string) => void }) {
  const [notes, setNotes] = useState('')
  const blockingIssues = issues.filter((issue) => !issue.severity || issue.severity === 'error')
  const hasBlockers = blockingIssues.length > 0
  return <div className="reviewer-simple-page"><section className="review-pdf-pane">{pdf}</section><aside className="review-decision-pane"><section className="review-card review-summary-card"><div><span>INVOICE DATA</span><h3>{title}</h3><p>{hasBlockers ? `${blockingIssues.length} issue${blockingIssues.length === 1 ? '' : 's'} must be resolved before approval.` : 'No validation blockers found.'}</p></div></section><section className="review-card reviewer-actions"><div className="decision-card-heading"><span>REVIEW DECISION</span><strong>Choose the outcome for this invoice</strong></div><label><span>Note, optional</span><textarea value={notes} placeholder="Example: Total and vendor match the PDF." onChange={(event) => setNotes(event.target.value)} /></label>{canDecide ? <>{hasBlockers ? <p className="decision-guidance"><AlertTriangle size={14} /> Fix the issues below or request a correction before approving.</p> : null}<div className="decision-choice-grid"><button className="approve-action" disabled={busy || hasBlockers} title={hasBlockers ? 'Resolve invoice issues before approving' : undefined} onClick={onApprove}><CheckCircle2 size={16} /> Approve</button><button className="request-action" disabled={busy} onClick={() => onCorrection(notes)}><Pencil size={16} /> Request correction</button><button className="reject-action" disabled={busy} onClick={() => onReject(notes)}><X size={16} /> Reject</button></div></> : <div className="decision-result">{status}</div>}{error ? <p className="form-error">{error}</p> : null}</section><section className="review-card compact-invoice-fields">{fields.map(([label, value]) => <div className={value === '-' ? 'field-missing' : ''} key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>{issues.length ? <section className="review-card review-issues"><strong><AlertTriangle size={15} /> Check these first</strong>{issues.slice(0, 3).map((issue, index) => <p key={index}>{issue.message ?? issue.field_name ?? issue.field ?? 'Invoice data'}</p>)}</section> : null}</aside></div>
}
